### ISSUE TITLE
compile error: mca/ess/lsf/ess_lsf_component.c:29:10: fatal error: lsf/lsbatch.h: No such file or directory

### ISSUE THREAD

**Issue by acolinisi** [openpmix/prrte#882]
PRRTE 621ad7f392496929819ad8afae27c1dd94856116

A regression introduced by e3914b0ad0df30939d329fe615a0ec37e64dcf2a. If I revert that commit on top of 621ad7f392 then PRRTE builds fine (and with `--enable-mca-dso=lm-lsf,ess-lsf,ras-lsf` works fine, too).

configure still detects LSF fine:

```
./configure \
--with-lsf=/opt/ibm/spectrumcomputing/lsf/10.1.0.9 \
--with-lsf-libdir=/opt/ibm/spectrumcomputing/lsf/10.1.0.9/linux3.10-glibc2.17-ppc64le-csm/lib \
...
```
```
--- MCA component ess:lsf (m4 configuration macro)
checking for MCA component ess:lsf compile mode... dso
checking --with-lsf value... sanity check ok (/opt/ibm/spectrumcomputing/lsf/10.1.0.9)
checking --with-lsf-libdir value... sanity check ok (/opt/ibm/spectrumcomputing/lsf/10.1.0.9/linux3.10-glibc2.17-ppc64le-csm/lib)
checking for library containing yp_all... -lnsl
checking for library containing shm_open... -lrt
checking lsf/lsf.h usability... yes
checking lsf/lsf.h presence... yes
checking for lsf/lsf.h... yes
checking for library containing ls_info... -llsf
checking if liblsf requires libnl v1 or v3... 
checking for LSF dir... /opt/ibm/spectrumcomputing/lsf/10.1.0.9 (from --with-lsf)
checking for LSF library dir... /opt/ibm/spectrumcomputing/lsf/10.1.0.9/linux3.10-glibc2.17-ppc64le-csm/lib (from --with-lsf-libdir)
checking lsf/lsbatch.h usability... yes
checking lsf/lsbatch.h presence... yes
checking for lsf/lsbatch.h... yes
checking for library containing lsb_launch... -lbat
checking if libbat requires libnl v1 or v3... configure: WARNING: Could not link a simple program with lib bat
checking for libevent conflict... No. LSF checks passed.
checking if MCA component ess:lsf can compile... yes
```

[prrte-config-log-lsf-missing-include.log](https://github.com/openpmix/prrte/files/6217623/prrte-config-log-lsf-missing-include.log)

But the `-I/opt/ibm/spectrumcomputing/lsf/10.1.0.9/include` flag doesn't make it onto the compile line:
```
libtool: compile:  powerpc64le-unknown-linux-gnu-gcc -DHAVE_CONFIG_H -I. \
-I/tmp/acolin-portage/portage/sys-cluster/prrte-2.9999_rc1/work/prrte-2.9999_rc1/src/mca/
ess/lsf -I../../../../src/include \
-iquote/tmp/acolin-portage/portage/sys-cluster/prrte-2.9999_rc1/work/prrte-2.9999_rc1 \
-iquote/tmp/acolin-portage/portage/sys-clu
ster/prrte-2.9999_rc1/work/prrte-2.9999_rc1-.ppc64 \
-iquote/tmp/acolin-portage/portage/sys-cluster/prrte-2.9999_rc1/work/prrte-2.9999_rc1/src/include -iquote/tmp/a
colin-portage/portage/sys-cluster/prrte-2.9999_rc1/work/prrte-2.9999_rc1-.ppc64/src/include \
-I/autofs/nccs-svm1_home1/acolin/casper/gpref/gp-k/usr/include \
-O3 -g 
-finline-functions -pthread \
-c /tmp/acolin-portage/portage/sys-cluster/prrte-2.9999_rc1/work/prrte-2.9999_rc1/src/mca/ess/lsf/ess_lsf_module.c \
 -fPIC -DPIC -o .libs/ess_lsf_module.o
/tmp/acolin-portage/portage/sys-cluster/prrte-2.9999_rc1/work/prrte-2.9999_rc1/\
src/mca/ess/lsf/ess_lsf_component.c:29:10: fatal error: lsf/lsbatch.h: No such file or directory
   29 | #include <lsf/lsbatch.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
```

With the above commit reverted, the `-I` flag makes it in:
```
libtool: compile:  powerpc64le-unknown-linux-gnu-gcc \
-DHAVE_CONFIG_H -I. \
-I/autofs/nccs-svm1_home1/acolin/casper/gpref/gp-k/tmp/portage/sys-cluster/prrte-2.9999/w
ork/prrte-2.9999/src/mca/ess/lsf -I../../../../src/include \
-I/opt/ibm/spectrumcomputing/lsf/10.1.0.9/include \
-iquote/autofs/nccs-svm1_home1/acolin/casper/gpref/gp
-k/tmp/portage/sys-cluster/prrte-2.9999/work/prrte-2.9999 \
-iquote/autofs/nccs-svm1_home1/acolin/casper/gpref/gp-k/tmp/portage/sys-cluster/prrte-2.9999/work/prrte-
2.9999-.ppc64 \
-iquote/autofs/nccs-svm1_home1/acolin/casper/gpref/gp-k/tmp/portage/sys-cluster/prrte-2.9999/work/prrte-2.9999/src/include \
-iquote/autofs/nccs-svm1_
home1/acolin/casper/gpref/gp-k/tmp/portage/sys-cluster/prrte-2.9999/work/prrte-2.9999-.ppc64/src/include \
-I/autofs/nccs-svm1_home1/acolin/casper/gpref/gp-k/usr/include \
-O3 -g -finline-functions -pthread \
-c /autofs/nccs-svm1_home1/acolin/casper/gpref/gp-k/tmp/portage/sys-cluster/prrte-2.9999/work/prrte-2.9999/src/mca/ess/lsf/ess_lsf_module.c  \
-fPIC -DPIC -o .libs/ess_lsf_module.o
```

(Note: the temp directories are different in these two builds so paths look different -- that's irrelevant.)

**Comment by rhc54** [comment]
I posted a PR to fix this - those include files are bogus. There is nothing in the ess/lsf component that utilizes LSF.
